using System.Globalization;
using Kiln.Internal.H264.Adaptation;
using Kiln.RateControl;
using Xunit;

namespace Kiln.Tests.AdaptiveRateControlTests;

/// <summary>
/// The backward-compatibility contract for wiring up the previously-unread
/// <see cref="EncoderNetworkFeedback"/> inputs (#24): a caller who supplies none of the new
/// signals — <c>EstimatedAvailableBitrateBps</c> at 0, <c>Jitter</c> at zero,
/// <c>ClientDecodeDelay</c> at null — must get decisions identical to v0.5.0, frame for frame.
/// <para>
/// <c>Fixtures/RateControlV050/decisions.csv</c> is a 600-frame decision transcript generated by
/// running exactly the scenario below against the v0.5.0 controller (commit <c>a3d3769</c>,
/// before any of the #24 changes). The scenario walks the controller through stability upshifts, a
/// sustained loss episode, an RTT spike into the severe tier, a queue backlog, a NACK burst, PLI /
/// FIR recovery, a scene-change IDR, and encode backpressure — with a 30 ms baseline RTT, where
/// the baseline-relative severe test is exactly equivalent to the old absolute 100 ms test.
/// Comparing decisions (not just "it still compiles") proves the sentinel paths are inert.
/// </para>
/// </summary>
public sealed class V050EquivalenceTests
{
    /// <summary>Serialize one decision the same way the fixture generator did.</summary>
    private static string Line(int frame, EncoderAdaptationDecision d, string lastReason) =>
        string.Create(CultureInfo.InvariantCulture,
            $"{frame},{d.TargetBitrateBps},{d.MaxFrameBytes},{d.TargetFps},{d.Width},{d.Height},{d.BaseQp},{(d.ForceIdr ? 1 : 0)},{(d.EnableIntraRefresh ? 1 : 0)},{(int)d.SpeedMode},{lastReason}");

    [Fact]
    public void DefaultSentinels_ReproduceV050Decisions_FrameForFrame()
    {
        var fixturePath = Path.Combine(
            AppContext.BaseDirectory, "Fixtures", "RateControlV050", "decisions.csv");
        var expected = File.ReadAllLines(fixturePath);
        Assert.Equal(600, expected.Length);

        var ctrl = new H264AdaptiveRateController(new RateControlConfig());
        for (var f = 0; f < 600; f++)
        {
            var loss = f is >= 120 and < 150 ? 0.05 : f is >= 300 and < 306 ? 0.12 : 0.0;
            var rttMs = f is >= 200 and < 210 ? 120 : f is >= 40 and < 45 ? 45 : 30;
            var queue = f is >= 400 and < 410 ? 250_000 : 5_000;
            var nacks = f is >= 500 and < 505 ? 10 : 0;
            var feedback = new EncoderNetworkFeedback(
                EstimatedAvailableBitrateBps: 0,
                PacketLossRatio: loss,
                RoundTripTime: TimeSpan.FromMilliseconds(rttMs),
                Jitter: TimeSpan.Zero,
                PendingRtpBytes: queue,
                NackCount: nacks,
                PictureLossIndication: f == 350,
                FullIntraRequest: f == 450,
                ClientDecodeDelay: null);
            var stats = new EncoderPipelineStats(
                LastEncodeDuration: TimeSpan.FromMilliseconds(3),
                AverageEncodeDuration: TimeSpan.FromMilliseconds(f is >= 550 and < 560 ? 15 : 3),
                PendingInputFrames: 1,
                PendingEncodedFrames: 0,
                DroppedInputFrames: 0,
                DroppedEncodedFrames: 0,
                LastEncodedFrameBytes: 15_000 + (f % 7) * 1000,
                LastFrameQp: 28,
                LastFrameWasIdr: false,
                MotionComplexity: 0.3,
                TextureComplexity: 0.5,
                SceneChangeDetected: f == 250);

            var d = ctrl.GetDecision(feedback, stats);
            ctrl.SyncAppliedState(d.Width, d.Height, d.TargetFps, d.SpeedMode);

            Assert.Equal(expected[f], Line(f, d, ctrl.LastAdaptationReason));
        }
    }
}
